name: Sync Upstream

on:
  schedule:
  - cron: '0 21 * * 1,3,5'
    # scheduled at 21:00 every Monday, Wednesday and Friday
  workflow_dispatch: # click the button on Github repo!

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo

    steps:
    - name: Checkout target repo
      uses: actions/checkout@v2
      with:
        ref: 13
        fetch-depth: 0

    - name: Fetch upstream changes
      run: |
        git remote add upstream https://android.googlesource.com/kernel/common -t android-4.14-stable --no-tags
        git fetch upstream -v

    - name: Merge upstream changes
      run: |
        git config --global user.name 'Github Action'
        git config --global user.email 'action@github.com'
        git merge upstream/android-4.14-stable --allow-unrelated-histories -v

    - name: Push changes
      run: |
        git push -v
